#! bin/bash

echo Opening .TextGrid and .wav files in Praat...

if 

# format is SUBJECT_STYPE_EXTENSION_dir
for directory in $(find . -name '*__dir'); do
	echo moving directory $directory ...
	directory=${directory/.\//}

	SUBJECT=${directory%7*}
	rem=${directory##*7}
	STYPE=${rem%8*}
	rem=${rem##*8}
	EXTENSION=${rem%__*}
	echo $SUBJECT
	echo $STYPE
	echo $EXTENSION
	[[ -d $PLACE ]] || mkdir $PLACE
	PLACE='./COSPRO_01/'$SUBJECT'/'$STYPE
	cd $PLACE
	mv $1/$directory $PLACE
	mv ./$directory ./$EXTENSION
	cd -
done

# for directory in $(find . -name '*txt__dir'); do
# 	echo moving directory $directory ...
# 	SUBJECT=${cut -d'_' -f1 $directory}
# 	STYPE=${echo $directory | cut -d'_' -f2}
# 	EXTENSION=${echo $directory | cut -d'_' -f3}
# 	echo $SUBJECT
# 	echo $STYPE
# 	echo $EXTENSION
# 	# mv $directory $EXTENSION
# 	# mv $directory ~/Desktop/Phonetics_Lab_Work/COSPRO_01/$SUBJECT/$STYPE/
# done